### Q2

In [2]:
s = "Lets Upgrade"
print(s.upper())

LETS UPGRADE


### Q3

In [5]:
# Function to calculate Profit. 
def Profit(costPrice, sellingPrice) : 
    profit = (sellingPrice - costPrice) 
    return profit 
  
# Function to calculate Loss. 
def Loss(costPrice, sellingPrice) : 
    Loss = (costPrice - sellingPrice) 
    return Loss 
  
# Main code 
if __name__ == "__main__" : 
  
    costPrice, sellingPrice = 19, 95
  
    if sellingPrice == costPrice : 
        print("No profit nor Loss") 
  
    elif sellingPrice > costPrice : 
        print("Profit")
        #print(Profit(costPrice, sellingPrice), "Profit") 
  
    else : 
        print("Loss") 

Profit


### Q4

In [ ]:
# pip install forex-python


In [6]:
import forex_python
from forex_python.converter import CurrencyCodes, CurrencyRates
test1 = CurrencyCodes()

test2 = CurrencyRates()

#fetching the Conversion rate
rate = test2.get_rate('EUR', 'INR')
print(rate)

#performing conversion
res = test2.convert('EUR', 'INR', 20)

#display result
print(res)

88.794
1775.8799999999999


### Q5 

In [30]:
# creating empty list
lst = [] 
  
# number of elemetns as input 
n = int(input("Enter number of elements : ")) 
  
# iterating till the range 
for i in range(0, n): 
    #if (i % 2 == 0):
        ele = int(input()
                  #lst = lst.append(ele)
        
print(lst.append(ele)) 
     

# # adding the element 
      
            



SyntaxError: invalid syntax (<ipython-input-30-a1f8e5d13d78>, line 13)

### Q6

In [2]:
#without list comprehension

for i in range(1,101):     
    if int(i**0.5)==i**0.5: 
        print(i) 


1
4
9
16
25
36
49
64
81
100


In [3]:
#with List Comprehension
[i for i in range(1,101) if int(i**0.5)==i**0.5]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

### Q7

In [4]:
n=int(input("Input a number "))
d = dict()

for x in range(1,n+1):
    d[x]=x*x

print(d)

Input a number 5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


### Q8

In [17]:
import math

x, y = 0, 0

while True:
    step = input("Type in UP/DOWN/LEFT/RIGHT #step number: ")

    if step == "":
        break

    else:
        step = step.split(" ")

        if step[0] == "UP":
            y = y + int(step[1])
        elif step[0] == "DOWN":
            y = y - int(step[1])
        elif step[0] == "LEFT":
            x = x - int(step[1])
        elif step[0] == "RIGHT":
            x = x + int(step[1])

c = math.sqrt(x**2 + y**2)

print("Distance:", c)

Type in UP/DOWN/LEFT/RIGHT #step number: 5
Type in UP/DOWN/LEFT/RIGHT #step number: 3
Type in UP/DOWN/LEFT/RIGHT #step number: 3
Type in UP/DOWN/LEFT/RIGHT #step number: 2
Type in UP/DOWN/LEFT/RIGHT #step number: 
Distance: 0.0


### Q9

In [18]:
import numpy as np
# Start = 2, Stop = 50, Step Size = 3
arr = np.arange(2, 50, 3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


### Q10 

In [28]:
#creating two lists
import numpy as np
lst1 = [] 
  
n = int(input("Enter number of elements : "))  
for i in range(0, n): 
    ele = int(input()) 
  
    lst1.append(ele)   
print(lst1) 

lst2 = [] 
  
n = int(input("Enter number of elements : "))  
for i in range(0, n): 
    ele = int(input()) 
  
    lst2.append(ele)   
print(lst2) 

#converting list into arrays

arr1 = numpy.array(lst1)
print ("List: ", lst1)

print ("Array: ", arr1)


arr2 = numpy.array(lst2)
print ("List: ", lst2)

print ("Array: ", arr2)

#concatenate and sorting arrays
arr3 = np.concatenate((arr1, arr2), axis=None)
arr3.sort(kind='mergesort')
print(arr3)

Enter number of elements : 5
2
3
1
7
6
[2, 3, 1, 7, 6]
Enter number of elements : 5
9
3
2
4
8
[9, 3, 2, 4, 8]
List:  [2, 3, 1, 7, 6]
Array:  [2 3 1 7 6]
List:  [9, 3, 2, 4, 8]
Array:  [9 3 2 4 8]
[1 2 2 3 3 4 6 7 8 9]


### Q11


In [29]:
#dimensions of a ndarray and its size
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

No. of dimensions:  2
Size of array:  6


### Q12 

In [31]:
# converting 1D array into 2D array

import numpy as np

# create 1D numpy array from a list
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr)

# Convert 1D array to a 2D numpy array of 2 rows and 3 columns
arr_2d = np.reshape(arr, (2, 5))
print('2D Numpy array:')
print(arr_2d)

1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
1D Numpy array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


### Q13 

In [32]:
# Horitzontal Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [33]:
# Vertical Stack
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


### Q14

In [34]:
# importing Counter module 
from collections import Counter 
  
input_list = [1, 2, 2, 5, 8, 4, 4, 8] 
  
# creating a list with the keys 
items = Counter(input_list).keys() 
print("No of unique items in the list are:", len(items)) 

No of unique items in the list are: 5


In [35]:
input_list = [1, 2, 2, 5, 8, 4, 4, 8] 
  
# converting our list to set 
new_set = set(input_list) 
print("No of unique items in the list are:", len(new_set))

No of unique items in the list are: 5
